# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('status', models.CharField(choices=[('1', '在线'), ('2', '维修'), ('3', '故障'), ('4', '未知')], max_length=256)),
                ('describe', models.TextField()),
                ('raw', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('status', models.CharField(choices=[('1', '启用'), ('2', '禁止'), ('3', '未知')], max_length=256)),
                ('describe', models.TextField()),
                ('raw', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='groups',
            field=models.ManyToManyField(to='assets.Groups'),
        ),
        migrations.AddField(
            model_name='assets',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetType'),
        ),
    ]
