# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='status',
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.CharField(choices=[('1', '在线'), ('2', '维修'), ('3', '故障'), ('4', '未知')], default=('2', '维修'), max_length=256),
        ),
    ]
