# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190314_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.CharField(choices=[('1', '在线'), ('2', '维修'), ('3', '故障'), ('4', '未知')], default=('1', '在线'), max_length=256),
        ),
        migrations.AlterField(
            model_name='groups',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='raw',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('2', '禁止'), ('3', '未知')], default=('1', '启用'), max_length=256),
        ),
    ]
