# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190314_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='raw',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='describe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='groups',
            name='raw',
            field=jsonfield.fields.JSONField(),
        ),
    ]
