# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20190314_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='raw',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
